name: lemmy
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0-116.0.dev

# Add regular dependencies here.
dependencies:
  dio: ^5.2.0+1
  dotenv: ^4.1.0
  json_annotation: ^4.8.1
  web_socket_channel: ^2.4.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.5
  json_serializable: ^6.7.0
  lints: ^2.0.0
  test: ^1.21.0
